/**TODO: В этом файле будет стор фильтра. */

export const OPTIONS_GENDER = [
  {
    label: 'Не имеет значения',
    value: 'default',
  },
  {
    label: 'Мужской',
    value: 'male',
  },
  {
    label: 'Женский',
    value: 'female',
  },
]

export const OPTIONS_ROLE = [
  {
    label: 'Всё',
    value: 'default',
  },
  {
    label: 'Хочу научиться',
    value: 'want-to-learn',
  },
  {
    label: 'Могу научить',
    value: 'can-teach',
  },
]

export const SKILLSFILTER_CATEGORY = [
  {
    id: '1',
    label: 'Бизнес и карьера',
    items: [
      { id: '1-1', label: 'Управление командой' },
      { id: '1-2', label: 'Маркетинг и реклама' },
      { id: '1-3', label: 'Продажи и переговоры' },
      { id: '1-4', label: 'Личный бренды' },
      { id: '1-5', label: 'Резюме и собеседование' },
      { id: '1-6', label: 'Тайм-менеджмент' },
      { id: '1-7', label: 'Проектное управление' },
      { id: '1-8', label: 'Предпринимательство' },
    ],
  },
  {
    id: '2',
    label: 'Творчество и искусство',
    items: [
      { id: '2-1', label: 'Рисование и иллюстрация' },
      { id: '2-2', label: 'Фотография' },
      { id: '2-3', label: 'Видеомонтаж' },
      { id: '2-4', label: 'Музыка и звук' },
      { id: '2-5', label: 'Актёрское мастерство' },
      { id: '2-6', label: 'Креативное письмо' },
      { id: '2-7', label: 'Арт-терапия' },
      { id: '2-8', label: 'Декор и DIY' },
    ],
  },
  {
    id: '3',
    label: 'Иностранные языки',
    items: [
      { id: '3-1', label: 'Английский' },
      { id: '3-2', label: 'Испанский' },
      { id: '3-3', label: 'Французский' },
      { id: '3-4', label: 'Немецкий' },
      { id: '3-5', label: 'Китайский' },
      { id: '3-6', label: 'Японский' },
      { id: '3-7', label: 'Подготовка к экзаменам (IELTS, TOEFL)' },
    ],
  },
  {
    id: '4',
    label: 'Образование и развитие',
    items: [
      { id: '4-1', label: 'Личностное развитие' },
      { id: '4-2', label: 'Навыки обучения' },
      { id: '4-3', label: 'Когнитивные техники' },
      { id: '4-4', label: 'Скорочтение' },
      { id: '4-5', label: 'Навыки преподавания' },
      { id: '4-6', label: 'Коучинг' },
    ],
  },
  {
    id: '5',
    label: 'Здоровье и лайфстайл',
    items: [
      { id: '5-1', label: 'Йога и медитация' },
      { id: '5-2', label: 'Питание и ЗОЖ' },
      { id: '5-3', label: 'Ментальное здоровье' },
      { id: '5-4', label: 'Осознанность' },
      { id: '5-5', label: 'Физические тренировки' },
      { id: '5-6', label: 'Сон и восстановление' },
      { id: '5-7', label: 'Баланс жизни и работы' },
    ],
  },
  {
    id: '6',
    label: 'Дом и уют',
    items: [
      { id: '6-1', label: 'Уборка и организация' },
      { id: '6-2', label: 'Домашние финансы' },
      { id: '6-3', label: 'Приготовление еды' },
      { id: '6-4', label: 'Домашние растения' },
      { id: '6-5', label: 'Ремонт' },
      { id: '6-6', label: 'Хранение вещей' },
    ],
  },
]

export const CITY_ROLE = [
  { label: 'Москва', value: 'Moscow' },
  { label: 'Санкт-Петербург', value: 'Saint-Petersburg' },
  { label: 'Новосибирск', value: 'Novosibirsk' },
  { label: 'Екатеринбург', value: 'Yekaterinburg' },
  { label: 'Казань', value: 'Kazan' },
  { label: 'Нижний Новгород', value: 'Nizhny-Novgorod' },
  { label: 'Челябинск', value: 'Chelyabinsk' },
  { label: 'Самара', value: 'Samara' },
  { label: 'Омск', value: 'Omsk' },
  { label: 'Ростов-на-Дону', value: 'Rostov-on-Don' },
  { label: 'Уфа', value: 'Ufa' },
  { label: 'Красноярск', value: 'Krasnoyarsk' },
  { label: 'Воронеж', value: 'Voronezh' },
  { label: 'Пермь', value: 'Perm' },
  { label: 'Волгоград', value: 'Volgograd' },
  { label: 'Краснодар', value: 'Krasnodar' },
  { label: 'Саратов', value: 'Saratov' },
  { label: 'Тюмень', value: 'Tyumen' },
  { label: 'Тольятти', value: 'Tolyatti' },
  { label: 'Ижевск', value: 'Izhevsk' },
  { label: 'Барнаул', value: 'Barnaul' },
  { label: 'Ульяновск', value: 'Ulyanovsk' },
  { label: 'Иркутск', value: 'Irkutsk' },
  { label: 'Хабаровск', value: 'Khabarovsk' },
  { label: 'Ярославль', value: 'Yaroslavl' },
  { label: 'Владивосток', value: 'Vladivostok' },
  { label: 'Махачкала', value: 'Makhachkala' },
  { label: 'Томск', value: 'Tomsk' },
  { label: 'Оренбург', value: 'Orenburg' },
  { label: 'Кемерово', value: 'Kemerovo' },
  { label: 'Новокузнецк', value: 'Novokuznetsk' },
  { label: 'Рязань', value: 'Ryazan' },
  { label: 'Астрахань', value: 'Astrakhan' },
  { label: 'Набережные Челны', value: 'Naberezhnye-Chelny' },
  { label: 'Пенза', value: 'Penza' },
  { label: 'Киров', value: 'Kirov' },
  { label: 'Липецк', value: 'Lipetsk' },
  { label: 'Чебоксары', value: 'Cheboksary' },
  { label: 'Калининград', value: 'Kaliningrad' },
  { label: 'Тула', value: 'Tula' },
  { label: 'Курск', value: 'Kursk' },
  { label: 'Ставрополь', value: 'Stavropol' },
  { label: 'Улан-Удэ', value: 'Ulan-Ude' },
  { label: 'Сочи', value: 'Sochi' },
  { label: 'Тверь', value: 'Tver' },
  { label: 'Магнитогорск', value: 'Magnitogorsk' },
  { label: 'Иваново', value: 'Ivanovo' },
  { label: 'Брянск', value: 'Bryansk' },
  { label: 'Белгород', value: 'Belgorod' },
  { label: 'Сургут', value: 'Surgut' },
]
