export { Catalog } from './Catalog/Catalog'
export { NotFound } from './NotFound/NotFound'
export { ServerError } from './ServerError/ServerError'
export { Home } from './Home/Home'
export { Login } from './Login/Login'
export { Registration1 } from './Registration1/Registration1'
export { ProfilePage } from './ProfilePage/ProfilePage'
export { Registration2 } from './Registration2/Registration2'
